import json
from pathlib import Path
from datetime import datetime

import streamlit as st
import pandas as pd
import plotly.express as px

# -------------------------------------------------
# Config
# -------------------------------------------------
st.set_page_config(
    page_title="Website Crawler Analytics",
    layout="wide",
)

METRICS_PATH = Path("/data/metrics/summary.json")

# -------------------------------------------------
# Helpers
# -------------------------------------------------
def load_summary(path: Path):
    if not path.exists():
        st.error("❌ summary.json not found. Run Airflow pipeline first.")
        st.stop()

    with open(path, "r") as f:
        return json.load(f)


# -------------------------------------------------
# Load data
# -------------------------------------------------
summary = load_summary(METRICS_PATH)

# -------------------------------------------------
# Header
# -------------------------------------------------
st.title("🌐 Website Crawler Analytics Dashboard")
st.caption("Metrics generated by Airflow pipeline")

st.markdown(
    f"""
**Last Aggregation Time:**  
{summary['aggregation_timestamp']}
"""
)

# -------------------------------------------------
# KPI Section
# -------------------------------------------------
col1, col2, col3, col4 = st.columns(4)

col1.metric("Total Websites", summary["total_websites_processed"])
col2.metric("Active Websites", summary["active_websites"])
col3.metric("Inactive Websites", summary["inactive_websites"])
col4.metric(
    "Websites with Case Studies",
    summary["num_websites_with_case_studies"],
)

# -------------------------------------------------
# Content Length Analytics
# -------------------------------------------------
st.subheader("📊 Content Length Statistics")

rows = []
for section, stats in summary["content_length_stats"].items():
    rows.append(
        {
            "Section": section,
            "Min Length": stats["min"],
            "Max Length": stats["max"],
            "Average Length": stats["avg"],
            "Count": stats["count"],
        }
    )

df = pd.DataFrame(rows)

st.dataframe(df, use_container_width=True)

# -------------------------------------------------
# Visualizations
# -------------------------------------------------
col1, col2 = st.columns(2)

with col1:
    fig_avg = px.bar(
        df,
        x="Section",
        y="Average Length",
        title="Average Content Length by Section",
        text="Average Length",
    )
    st.plotly_chart(fig_avg, use_container_width=True)

with col2:
    fig_range = px.bar(
        df,
        x="Section",
        y=["Min Length", "Max Length"],
        title="Content Length Range by Section",
        barmode="group",
    )
    st.plotly_chart(fig_range, use_container_width=True)

# -------------------------------------------------
# Footer
# -------------------------------------------------
st.markdown("---")
st.caption("Built with Streamlit • Powered by Airflow")
